### ISSUE TITLE
LED State Synchronization and New Resistor Ladder

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#401] opened 2022-11-17 17:48 UTC
setup ipMidi between two PedalinoMini #58
When PedalinoMIni receives from any supported interface a NoteOn/CC/PC midi message corresponding to a pedal it turn on (or off) the corresponding led.

I used two PEDALINOMINI to test and found that only when receiving PC signal, the corresponding LED will be turned on or off. When receiving CC and NOTE signal, only the screen will display the received MIDI signal.

Another question, can the type of resistance ladder in the picture be realized? If it can be realized, then one controller port supports 7 independent switches, and a total of 42 switches can be expanded
![Snipaste_2022-11-19_13-17-13](https://user-images.githubusercontent.com/91867813/202835665-bde6b6bb-4b96-4a92-88e3-5bbb98f08600.png)

**Comment by alf45tar** [comment] 2022-11-20 16:54
The circuit is working fine but it requires a lot of changes in the software with no value. If you need more buttons increase the LADDER_STEPS and recalculate the resistors.

**Comment by alf45tar** [comment] 2022-11-20 20:06
Check version 3.0.3 for led synchronisation fix

**Comment by AndreySom** [comment] 2022-11-28 00:20
First, I'd like to thank you @alf45tar  for such a nice project. I've built mine and it works like a charm. I became a sponsor today, and I had the same led sync question as bob posted above. I'd like to know where can i find version 3 to test it. I'm using IPMidi.

**Comment by alf45tar** [comment] 2022-11-28 13:36
@AndreySom I added you to the private repository. You should have received an email.

**Comment by alf45tar** [comment] 2022-11-28 15:04
Very strange. I didn't change too much in the WebUI this time. It seems it is mix of 2 pages: Controls and Options.

**Comment by alf45tar** [comment] 2022-12-04 13:52
Sill an issue?

**Comment by bobvc133** [comment] 2022-12-05 15:26
> Sill an issue?

3.0.4 firmware, when editing the transient effect, the PRESS and RELEASE actions can still only set the OFF color, so the LED brightness is always OFF brightness, and it is strange when editing the NOTE ON and NOTE OFF actions, the ON and OFF colors of the RELEASE action can be set setting, but the ON color cannot be synchronized, and the option page encoder layout problem still exists

**Comment by alf45tar** [comment] 2022-12-10 18:46
I am not able to reproduce the Options page layout issue. It works fine for me and I have no evidence from others.
Did you try to cancel the cache of the browser? Did you uploaded the new filesystem image? Did you try to fully erase before flash the new firmware?

**Comment by bobvc133** [comment] 2022-12-11 04:15
> I am not able to reproduce the Options page layout issue. It works fine for me and I have no evidence from others. Did you try to cancel the cache of the browser? Did you uploaded the new filesystem image? Did you try to fully erase before flash the new firmware?

1. Every time I burn the firmware, I will erase it, and then recompile and upload the firmware and file system image. My browser has always disabled the caching function. The test uses the original firmware and only modifies the port.
![Snipaste_2022-12-11_11-46-33](https://user-images.githubusercontent.com/91867813/206886072-7b33e117-c5e7-4be8-ab4d-2872c8cc7c47.png)
![Snipaste_2022-12-11_11-46-52](https://user-images.githubusercontent.com/91867813/206886073-1f702117-8ae5-4daa-be5f-33b58710bc59.png)
![Snipaste_2022-12-11_11-47-56](https://user-images.githubusercontent.com/91867813/206886075-9359f6de-7616-497a-b49c-1d80754c4982.png)3
![Snipaste_2022-12-11_11-47-26](https://user-images.githubusercontent.com/91867813/206886074-be0cf0fa-33e6-47fc-bac7-6581f7cd8b71.png)
2. There are still problems with the layout of the encoder bar on the 3.0.5 firmware option page in various resolutions
3. There are still problems with the LED setting and status synchronization of the instantaneous action of the 3.0.5 firmware
4. I also found a problem that the CC action of the instant effect can only be set in TAG1, and the NOTE action can only be set in TAG2.
![Snipaste_2022-12-11_12-00-06](https://user-images.githubusercontent.com/91867813/206886081-bbd7c171-fdfd-4555-aaaf-6639fb949d1f.png)
![Snipaste_2022-12-11_12-01-15](https://user-images.githubusercontent.com/91867813/206886084-c9c7f09e-e033-45da-8341-a7d2585f7eee.png)

**Comment by alf45tar** [comment] 2022-12-11 12:45
Encoders tile when on single column fixed in version 3.0.6.
Tag1 and Tag2 are used as is by design. It is not considered a bug. May be in some next version I will create anything more coherent.
Can you be more specific on point 3?

**Comment by bobvc133** [comment] 2022-12-11 14:17
> Encoders tile when on single column fixed in version 3.0.6. Tag1 and Tag2 are used as is by design. It is not considered a bug. May be in some next version I will create anything more coherent. Can you be more specific on point 3?

First of all, set the press and release actions at the same time, the ON color setting of the press is invalid, only the OFF color can be set, so the LED brightness can only be OFF brightness. The Note Off Release action can set the ON color, but CC cannot. In the end, the LED status cannot be synchronized. These problems all occur in the momentary effect.
![Snipaste_2022-12-11_21-51-31](https://user-images.githubusercontent.com/91867813/206908986-c03e32fe-e4e5-49dc-be16-f0e221f6406b.png)
![Uploading Snipaste_2022-12-11_22-17-30.png…]()

**Closed** 2023-01-07 19:02 UTC
Labels: bug
