### ISSUE TITLE
OLED display faulty on update.

### ISSUE THREAD

**Issue by jimhiggs** [alf45tar/PedalinoMini#79] opened 2020-02-27 19:25 UTC
Latest version.
Display on update looks like this: 
It is writing over A 01
![IMG_20200227_151743240](https://user-images.githubusercontent.com/33665935/75479061-50364100-5975-11ea-8bb8-823202404b67.jpg)

**Comment by alf45tar** [comment] 2020-02-27 19:49
Did you try with previous version?

**Comment by jimhiggs** [comment] 2020-02-27 19:56
Sorry yes, it has been like that for a while but before that I was crashing before writing to oled.

**Comment by alf45tar** [comment] 2020-03-03 16:42
Did you solved? If the issue is still presen check the hardware connections.

**Comment by jimhiggs** [comment] 2020-03-03 16:55
Unless you have a new update (less than 5 days old) then it is still present. I don't see how it can be a hardware issue as the oled works perfectly normally, it is only the update that screws up the screen.

**Comment by alf45tar** [comment] 2020-03-04 07:49
Now it is clear to me. The screen is corrupted during uploading the new firmware not after the update.
I don't have the issue. Are you using OTA update or via USB?

**Comment by jimhiggs** [comment] 2020-03-04 13:34
Sorry I was not clear. During OTA, the progress bar is corrupted.

**Comment by alf45tar** [comment] 2020-03-10 22:29
Display cannot be updated during firmware update via HTTP because there are no enough CPU resources. Update progress is not anymore reported on OLED but only on leds.
If you give a try to the latest version it should be fixed.

**Closed by alf45tar** 2020-03-10 22:29 UTC
Labels: bug
